# Docker Composeのバージョンを指定
version: "3"

# サービス定義
services:
  # Next.jsアプリケーションのサービス
  nodeapp:
    # コンテナ名を指定
    container_name: nodesecond
    # 使用するイメージ名
    image: nodesecond
    # ビルド設定
    build:
      # ビルドコンテキストをtestnextディレクトリに設定
      context: ./testnext
      # 使用するDockerfileを指定
      dockerfile: Dockerfile
    # 環境変数の設定
    environment:
      # プロダクションモードを有効化
      - NODE_ENV=production
      # すべてのネットワークインターフェースでリッスン
      - HOSTNAME=0.0.0.0
    # ポートマッピング
    ports:
      # ホストの3002番ポートをコンテナの3000番ポートにマッピング
      - "3002:3000"